
-- Users table extensions (managed by Supabase Auth, but usually we need a public profiles table)
-- This table references the internal `auth.users` via the `id` column.
create table public.users (
  id uuid references auth.users not null primary key,
  full_name text,
  avatar_url text,
  billing_address jsonb,
  payment_method jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.users enable row level security;

-- Agents Table
create table public.agents (
  id bigint generated by default as identity primary key,
  owner_id uuid references public.users(id) not null,
  name text not null,
  description text,
  price decimal(10,2) not null, -- One-time purchase price
  rental_price decimal(10,2),   -- Optional rental price per month
  features jsonb,               -- List of features
  image_url text,
  is_for_sale boolean default true,
  is_for_rent boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.agents enable row level security;

-- Purchases (One-time buys)
create table public.purchases (
  id bigint generated by default as identity primary key,
  buyer_id uuid references public.users(id) not null,
  agent_id bigint references public.agents(id) not null,
  amount decimal(10,2) not null,
  stripe_payment_id text,
  status text default 'completed', -- pending, completed, refunded
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.purchases enable row level security;

-- Rentals (Subscriptions)
create table public.rentals (
  id bigint generated by default as identity primary key,
  renter_id uuid references public.users(id) not null,
  agent_id bigint references public.agents(id) not null,
  start_date timestamp with time zone default timezone('utc'::text, now()) not null,
  end_date timestamp with time zone, -- Null means ongoing subscription
  status text default 'active',      -- active, cancelled, expired, past_due
  stripe_subscription_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.rentals enable row level security;

-- Payments (Transaction Log)
create table public.payments (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) not null,
  amount decimal(10,2) not null,
  currency text default 'usd',
  status text not null,       -- succeeded, pending, failed
  stripe_charge_id text,
  metadata jsonb,             -- Extra details (e.g., purchase_id, rental_id)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.payments enable row level security;

-- RLS Policies (Basic examples)

-- Users can read their own profile
create policy "Users can view own profile" on public.users
  for select using (auth.uid() = id);

-- Users can update their own profile
create policy "Users can update own profile" on public.users
  for update using (auth.uid() = id);

-- Everyone can view agents
create policy "Anyone can view agents" on public.agents
  for select using (true);

-- Only owners can update their agents
create policy "Owners can update agents" on public.agents
  for update using (auth.uid() = owner_id);

-- Only owners can insert agents
create policy "Authenticated users can insert agents" on public.agents
  for insert with check (auth.uid() = owner_id);
